### ISSUE TITLE
[Manutenção 1] Incremento na funcionalidade Inserção de Item Bibliográfico, para as categorias book e article.

### ISSUE THREAD

**Issue by Lufscar** [Lufscar/DC-UFSCar-ES2-201902-GrupoMaisPerdido#1]
Validar os seguintes campos de acordo com as seguintes regras:
 Year: deve ser um ano válido (de acordo com o calendário da linguagem
Java)
 Bibtexkey: definido pelo usuário ou automaticamente, deve ter no mínimo 2
caracteres, sendo o primeiro uma letra maiúscula ou minúscula

**Comment by Lufscar** [comment]
Utilizar a Branch Manutenção-1

**Comment by jcinel** [comment]
pull request #4 criado para essa issue

**Comment by Lufscar** [comment]
closes #1
