### ISSUE TITLE
[Manutenção 3] Manutenção Perfectiva Extra

### ISSUE THREAD

**Issue by Lufscar** [Lufscar/DC-UFSCar-ES2-201902-GrupoMaisPerdido#3]
Definir e realizar uma manutenção PERFECTIVA que se refere à melhoria de uma
funcionalidade qualquer existente, diferente das manutenções especificadas nas outras Issues.

**Comment by Lufscar** [comment]
Utilizar a Branch Manutenção-3

**Comment by jcinel** [comment]
Resolvido
